name: Codecov

on:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

permissions: read-all

jobs:
  codecov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71
      - uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281
        with:
          go-version: '1.17'
      -
        name: Generate Code Coverage Report
        run: make code-cov-report
      -
        name: Upload Report to Codecov
        uses: codecov/codecov-action@b049ab51f46ef6cd9c7ca52a856631a818969c7c
        with:
          file: ./coverage.out
          fail_ci_if_error: true
          verbose: true