name: e2e
on:
  push:
    branches:
      - 'main'
      - 'release*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/config.yml'
  pull_request:
    branches:
      - 'main'
      - 'release*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '.github/config.yml'

permissions: read-all

jobs:
  e2e-test:
    strategy:
      fail-fast: false
      matrix:
        k8s-version: [v1.16.15, v1.17.17, v1.18.19, v1.19.11, v1.20.7, v1.21.2, v1.22.5, v1.23.3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go 
        uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281
        with:
          go-version: 1.17

      - name: Set up Helm
        uses: azure/setup-helm@fa870ea9a2311ef874f865648d372bb03dd520ba
        with:
          version: v3.5.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a

      - name: Cache Go modules
        uses: actions/cache@2d8d0d1c9b41812b6fd3d4ae064360e7d8762c7b
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name :  Create dev images, kind cluster and setup kustomize
        run: |
          export KIND_IMAGE=kindest/node:${{ matrix.k8s-version }}
          make create-e2e-infrastruture

      - name: e2e testing
        run: |
          echo ">>> Install Kyverno"
          sed 's/imagePullPolicy:.*$/imagePullPolicy: IfNotPresent/g' ${GITHUB_WORKSPACE}/config/install.yaml | kubectl apply -f -
          kubectl apply -f ${GITHUB_WORKSPACE}/config/github/rbac.yaml
          chmod a+x ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh
          sleep 50
          echo ">>> Check kyverno"
          kubectl get pods -n kyverno
          ${GITHUB_WORKSPACE}/scripts/verify-deployment.sh -n kyverno  kyverno
          sleep 20
          echo ">>> Expose the Kyverno's service's metric server to the host"
          kubectl port-forward svc/kyverno-svc-metrics -n kyverno 8000:8000 &
          echo ">>> Run Kyverno e2e test"
          make test-e2e
          kubectl delete -f ${GITHUB_WORKSPACE}/config/install.yaml

      - name: Update chart values
        run: |
          make helm-test-values
          cat charts/kyverno/values.yaml

      - name: Run chart-testing (install)
        run: |
          kubectl create namespace kyverno
          ct install --target-branch=main --namespace=kyverno --charts charts/kyverno

      - name: Run chart-testing (policies)
        run: |
          helm install kyverno charts/kyverno -n kyverno
          ct install --target-branch=main --namespace=kyverno --charts charts/kyverno-policies

      - name: Debug failure
        if: failure()
        run: |
          kubectl get mutatingwebhookconfigurations,validatingwebhookconfigurations
          kubectl -n kyverno get pod
          kubectl -n kyverno describe pod | grep -i events -A10
          kubectl -n kyverno logs deploy/kyverno
