name: helm-release
on:
  push:
    tags:
      - 'helm-chart-v*'

permissions: 
  contents: read
  packages: write
  id-token: write 

jobs:
  helm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71

      - name: Unshallow
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@6c048c755810cf9ec19b2a2a75014fcd1aa0c9c6
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a

      - name: Run chart-testing (lint)
        run: ct lint --target-branch=main --check-version-increment=false

  create-release:
    runs-on: ubuntu-latest
    needs: helm-tests
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71
        with:
          fetch-depth: 0
          
      - name: Install Helm
        uses: azure/setup-helm@fa870ea9a2311ef874f865648d372bb03dd520ba
        with:
          version: v3.4.1

      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@b43a8719cc63fdb3aa943cc57359ab19118eab3f
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          linting: off
