name: tests
on:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

permissions: 
  contents: read
  packages: write
  id-token: write 

jobs:
  pre-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@2d8d0d1c9b41812b6fd3d4ae064360e7d8762c7b
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: gofmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -ne 0 ]
          then
           echo "The following files were found to be not go formatted:"
           gofmt -s -l .
           echo "Please run 'make fmt' to go format the above files."
           exit 1
          fi

      - name: goimports
        run: |
          if [ "$(goimports -l . | wc -l)" -ne 0 ]
          then
           echo "The following files were found to have import formatting issues:"
           goimports -l -l .
           echo "Please run 'make fmt' to go format the above files."
           exit 1
          fi

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@5d76ca8ed91cee8dc262f1e6bbe74f4b1bf3f204

      - name: Checking unused pkgs using go mod tidy
        run: |
          make unused-package-check

      - name: Verify generated code is up to date
        run: make verify-codegen

  tests:
    runs-on: ubuntu-latest
    needs: pre-checks
    steps:
      - name: Checkout
        uses: actions/checkout@d50f8ea76748df49594d9b109b614f3b4db63c71

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@a5865a93f26fcb9014b34e4be3fb246a9691a281
        with:
          go-version: 1.17

      - name: Cache Go modules
        uses: actions/cache@2d8d0d1c9b41812b6fd3d4ae064360e7d8762c7b
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Kyverno unit test
        run: |
          export PROJECT_PATH=$(pwd)
          make test-unit
